---

- name: Debian | Set default_debian_distribution
  ansible.builtin.set_fact:
    default_debian_distribution: "{{ ansible_distribution_release }}"
  when: default_debian_distribution is not defined

- name: Debian | Install pre-requisites
  ansible.builtin.apt:
    name:
      - lsb-release
    state: present

- name: Debian | Install additional packages
  ansible.builtin.apt:
    pkg: "{{ backports_internal_additional_packages }}"
    state: present
  when: backports_internal_additional_packages | length > 0

- name: Debian | Add backports repository
  block:
    - name: Set Debian release
      ansible.builtin.apt_repository:
        repo: >-
          deb {{ backports_internal_uri }}
          {{ ansible_distribution_release }}-backports
          {{ backports_internal_components }}
        state: present
        update_cache: true
    - name: Set backports
      ansible.builtin.set_fact:
        debian_release: '{{ default_debian_distribution + "-backports" }}'
  when: debian_use_backports

- name: Debian | Install ZFS
  ansible.builtin.apt: 
    name:
      - linux-headers-{{ ansible_kernel }}
      - zfsutils-linux
      - zfs-dkms
    state: present
    default_release: "{{ debian_release }}"

- name: Debian | Enable ZFS module
  community.general.modprobe:
    name: zfs
    state: present

- name: Debian | Install open-iscsi (if enabled)
  ansible.builtin.apt:
    name:
      - open-iscsi 
    state: present
  when: >
        zfs_enable_iscsi is defined and
        zfs_enable_iscsi

- name: Debian | Uninstall open-iscsi (if not enabled)
  ansible.builtin.apt:
    name:
      - open-iscsi
    state: absent
  when: >
    zfs_enable_iscsi is defined and
    not zfs_enable_iscsi

- name: Debian | Configure iscsitarget service
  ansible.builtin.template:
    src: etc/default/iscsitarget.j2
    dest: /etc/default/iscsitarget
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart iscsitarget
  when: >
    zfs_enable_iscsi is defined and
    zfs_enable_iscsi

- name: Debian | Install NFS (if enabled)
  ansible.builtin.apt:
    name: nfs-kernel-server
    state: present
  when: >
    zfs_enable_nfs is defined and
    zfs_enable_nfs

- name: Debian | Uninstall NFS (if not enabled)
  ansible.builtin.apt:
    name: nfs-kernel-server
    state: absent
  when: >
    zfs_enable_nfs is defined and
    not zfs_enable_nfs

- name: Debian | Configure NFS Kernel Server
  ansible.builtin.template:
    src: etc/exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart nfs-kernel-server
    - Start zfs-share
  when: >
    zfs_enable_nfs is defined and
    zfs_enable_nfs

- name: Debian | Configure ZFS
  ansible.builtin.template:
    src: etc/default/zfs.j2
    dest: /etc/default/zfs
    owner: root
    group: root
    mode: "0644"
  notify:
    - Start zfs-share
