---
- name: Tune ZFS | Configure ZFS performance tuning
  ansible.builtin.template:
    src: etc/modprobe.d/zfs.conf.j2
    dest: /etc/modprobe.d/zfs.conf
    owner: root
    group: root
    mode: "0644"
