---
# handlers file for ansible-zfs
- name: Restart iscsitarget
  ansible.builtin.service:
    name: "iscsitarget"
    state: restarted
  when: >
    zfs_enable_iscsi is defined and
    zfs_enable_iscsi

- name: Restart nfs-kernel-server
  ansible.builtin.service:
    name: "nfs-kernel-server"
    state: restarted

- name: Restart samba
  ansible.builtin.service:
    name: "smbd"
    state: "restarted"

- name: Start zfs-share
  ansible.builtin.service:
    name: "zfs-share"
    state: started
